export const profile = {
  bio: [
    'Nguyen Minh Hang / Nora Wilde is an Interdisciplinary Fashion Creative, raised and resides in Hanoi, Vietnam.',
    'Her experience spans textiles & fashion design, concept development, creative and art direction, visual storytelling, and other interdisciplinary practice for fashion, film, theatre and cultural productions in both commercial and conceptual environments.',
    'Growing up on the sideline of Vietnamese heritage and Western cultural influence, Nora’s work centered the human factor and emphasized the complex relationship in-between culture, community, and politics; utilizing the language of sustainability, crafts and experimentation.',
    'She believes that in today’s dominant capitalist fashion system, products and profits have become the focus and therefore have ignored the human experience. Her ultimate goal is to offer a more personal, intentional and craft-based experience that generates more awareness and transforms people’s view of the world through fashion.',
    'Nora has a HND in Fashion & Textiles Design from London College of Design & Fashion - Hanoi, and previously spent 2 years at Hanoi College of Arts studied Fashion Design.',
  ],
};

export const categories = [
  {
    slug: 'fashion-costume',
    title: 'fashion & costume',
    description: 'soft tailoring, performance garments, speculative wardrobe and costume-led storytelling.',
  },
  {
    slug: 'creative-direction',
    title: 'creative/art direction',
    description: 'image worlds, theatre atmosphere, campaign rhythm and visual direction across disciplines.',
  },
  {
    slug: 'visual-art',
    title: 'visual art',
    description: 'posters, film fragments, hand-drawn studies and color-led visual experiments.',
  },
  {
    slug: 'props-accessories',
    title: 'props & accessories',
    description: 'objects, shoes, bags and strange little devices made for bodies and scenes.',
  },
  {
    slug: 'research',
    title: 'research',
    description: 'material culture, craft histories and field notes translated into image and garment systems.',
  },
  {
    slug: 'photography',
    title: 'photography',
    description: 'personal visual essays, documentation, tests and quiet observational frames.',
  },
  {
    slug: 'writing',
    title: 'writing',
    description: 'arts writing, translation and short texts around fashion, culture and the politics of making.',
  },
];

const cyberPortfolio = [
  '/assets/real/sheet/cyber-portfolio/website-portfolio-03.png',
  '/assets/real/sheet/cyber-portfolio/website-portfolio-04.png',
  '/assets/real/sheet/cyber-portfolio/website-portfolio-05.png',
  '/assets/real/sheet/cyber-portfolio/website-portfolio-06.png',
  '/assets/real/sheet/cyber-portfolio/website-portfolio-07.png',
  '/assets/real/sheet/cyber-portfolio/website-portfolio-08.png',
  '/assets/real/sheet/cyber-portfolio/website-portfolio-10.png',
];

const cyberPhotoshoot = [
  '/assets/real/nora-term-4428.png',
  '/assets/real/nora-term-4434.png',
  '/assets/real/nora-term-4467.png',
  '/assets/real/nora-term-4476.png',
  '/assets/real/nora-term-4536.png',
  '/assets/real/nora-term-4570.png',
  '/assets/real/nora-term-4640.png',
  '/assets/real/nora-term-4652.png',
  '/assets/real/nora-term-4695.png',
  '/assets/real/nora-term-4703.png',
  '/assets/real/nora-term-4717.png',
  '/assets/real/nora-term-4721.png',
  '/assets/real/nora-term-4728.png',
  '/assets/real/nora-term-4927-a.png',
  '/assets/real/nora-term-4927-b.png',
  '/assets/real/nora-term-4935.png',
  '/assets/real/nora-term-4971.png',
  '/assets/real/nora-term-5031.png',
  '/assets/real/nora-term-5139.png',
];

const vesselPortfolio = [
  '/assets/real/sheet/vessel-portfolio/website-portfolio-13.png',
  '/assets/real/sheet/vessel-portfolio/website-portfolio-14.png',
  '/assets/real/sheet/vessel-portfolio/website-portfolio-15.png',
  '/assets/real/sheet/vessel-portfolio/website-portfolio-16.png',
  '/assets/real/sheet/vessel-portfolio/website-portfolio-17.png',
  '/assets/real/sheet/vessel-portfolio/website-portfolio-18.png',
  '/assets/real/sheet/vessel-portfolio/website-portfolio-19.png',
];

const vesselPhotoshoot = [
  '/assets/real/sheet/vessel-photoshoot/nora-0001-1.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0059.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0152.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0191.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0350.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0414.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0442.jpeg',
  '/assets/real/sheet/vessel-photoshoot/nora-0459.jpeg',
];

const odePortfolio = [
  '/assets/real/sheet/ode-portfolio/website-portfolio-22.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-23.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-24.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-25.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-26.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-27.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-28.png',
  '/assets/real/sheet/ode-portfolio/website-portfolio-29.png',
];

const odePhotoshoot = [
  '/assets/real/sheet/ode-photoshoot/01.png',
  '/assets/real/sheet/ode-photoshoot/02.png',
  '/assets/real/sheet/ode-photoshoot/03.png',
  '/assets/real/sheet/ode-photoshoot/04.png',
  '/assets/real/sheet/ode-photoshoot/05.png',
  '/assets/real/sheet/ode-photoshoot/06.png',
];

const ballPointGallery = [
  '/assets/real/sheet/visual-ballpoint/cover.png',
  '/assets/real/sheet/visual-ballpoint/img-2175.jpeg',
  '/assets/real/sheet/visual-ballpoint/img-2176.jpeg',
  '/assets/real/sheet/visual-ballpoint/img-2177.jpeg',
  '/assets/real/sheet/visual-ballpoint/img-2517-original.jpeg',
  '/assets/real/sheet/visual-ballpoint/img-5188.jpeg',
];

const ballPointInfo = [
  { title: 'ball-point pen series', meta: 'cover, 2021-2023' },
  { title: 'ball-point pen drawing', meta: 'pen on paper, 2021-2023' },
  { title: 'ball-point pen drawing', meta: 'pen on paper, 2021-2023' },
  { title: 'ball-point pen drawing', meta: 'pen on paper, 2021-2023' },
  { title: 'ball-point pen drawing', meta: 'pen on paper, 2021-2023' },
  { title: 'ball-point pen drawing', meta: 'pen on paper, 2021-2023' },
];

const coloredGallery = [
  '/assets/real/sheet/visual-colored/cover.png',
  '/assets/real/sheet/visual-colored/img-0655-original.jpeg',
  '/assets/real/sheet/visual-colored/img-1593-original.jpeg',
  '/assets/real/sheet/visual-colored/img-2181.jpeg',
  '/assets/real/sheet/visual-colored/img-2182.jpeg',
  '/assets/real/sheet/visual-colored/img-2183.jpeg',
];

const coloredInfo = [
  { title: 'colored series', meta: 'cover, 2021-2024' },
  { title: 'colored study', meta: 'acrylic / watercolor, 2021-2024' },
  { title: 'colored study', meta: 'acrylic / watercolor, 2021-2024' },
  { title: 'colored study', meta: 'acrylic / watercolor, 2021-2024' },
  { title: 'colored study', meta: 'acrylic / watercolor, 2021-2024' },
  { title: 'colored study', meta: 'acrylic / watercolor, 2021-2024' },
];

export const projects = [
  {
    slug: 'cyber-survivalism',
    category: 'fashion-costume',
    title: 'cyber survivalism',
    subtitle: 'soft tailoring project - 2025',
    year: '2025',
    cover: cyberPortfolio[0],
    gallery: cyberPortfolio,
    photoshoot: cyberPhotoshoot,
    videoTitle: 'fashion film',
    filmUrl: 'https://youtu.be/vU_7N2FZ4QQ?si=qAj5qpWyS7lO3UNB',
    filmThumbnail: cyberPortfolio[0],
    description:
      'CYBER SURVIVALISM imagines a near-apocalyptic world where pollution overloaded the surface of the planet and resources became a scarcity - a world of nostalgia for a seemingly peaceful past and everlasting hope in a brighter future. Clothings surpass the mere meaning of personal statement to become an united political expression, questioning the social norms and challenging the status quo. Humanity scrapes all they could from landfills to shield themselves from the world - each became a soldier with their own armor. Rooted in the complex integration of sustainability, politics and technology in fashion; CYBER SURVIVALISM brought together retro futurism and cyberpunk aesthetic in an effort of capturing indomitable human spirits amid a doomed reality, through the language of recycled materials and funkiness.',
    credits: [
      ['creative director, fashion designer', 'Nora Wilde'],
      ['instructors', 'Lisa Shawgi, Tu Dang'],
      ['starring', 'Dung Le'],
      ['photography & lighting', 'Vu Viet Manh'],
      ['videographer', 'Hong Minh'],
      ['editor & vfx', 'Vu Ngoc'],
      ['composer', 'Katherine Vu'],
      ['m.u.a', 'Hiep Ciao'],
      ['technical consultant', 'Grace Nguyen'],
      ['projector content & logistic support', 'Dang Khoi Hoang'],
      ['on-set support', 'Dang Khoi Hoang, Vu Ngoc, Dinh Bao Thuong'],
      ['special thanks', 'Grace Nguyen, Pham Khanh Linh, Vinh Nguyen, Bui Manh Duong'],
    ],
  },
  {
    slug: 'amidst-alienation-belonging',
    category: 'fashion-costume',
    title: 'amidst alienation & belonging',
    subtitle: 'fashion image study - 2025',
    year: '2025',
    cover: '/assets/real/img-1497-original.png',
    gallery: ['/assets/real/img-1497-original.png', '/assets/real/img-1734.png', '/assets/real/img-2340.png'],
    description:
      'A study of bodies negotiating tenderness, exile and community through garment proportion, silence and saturated negative space.',
    credits: [['creative direction', 'Nora Wilde']],
  },
  {
    slug: 'vessel-of-soul',
    category: 'fashion-costume',
    title: 'vessel of soul',
    subtitle: 'evening wear project - 2025',
    year: '2025',
    cover: vesselPortfolio[0],
    gallery: vesselPortfolio,
    photoshoot: vesselPhotoshoot,
    videoTitle: 'fashion film',
    filmUrl: 'https://youtu.be/jWnNC52O35o?si=C3VCU1the76ghUop',
    filmThumbnail: vesselPortfolio[0],
    description:
      'Plato’s “Symposium” recorded an ancient Aristophanes’ story on the myth of the soulmates: Humankind were originally sculpted with 4 arms, 4 legs, and a head of 2 faces - they were created as a whole. Fearing the swelling power lurking in these harmonious beings, Zeus halved each human, dividing one soul between two bodies. Vessel of Soul emerged from my interpretation of the story, hoping to redefine soulmate as an intermingling of journeys to unity - a balancing point of desire, solace, tranquility and fullness within oneself, and towards the world.',
    credits: [
      ['creative director, fashion designer', 'Nora Wilde'],
      ['instructors', 'Donna Bramhall, Vu Ta Linh, Tu Dang'],
      ['photographer', 'Vu Viet Manh'],
      ['videographer', 'Hong Minh'],
      ['editor & vfx', 'Vu Ngoc'],
      ['composer', 'Katherine Vu'],
      ['starring', 'Thuc Anh'],
      ['hand models', 'Alice To, Vu Viet Manh, Khanh Doan'],
      ['m.u.a', 'Hiep Ciao'],
      ['lighting', 'Hong Minh, Vu Viet Manh'],
      ['set design support', 'Alice To, Laine'],
      ['accessories support', 'Hang Hang, Alice To'],
      ['textiles support', 'Hang Hang, Nhat Minh Bui, Lasmpie, Alice To, Phan Minh Trang, Laine'],
      ['on-set support', 'Alice To, Nhat Minh Bui, Khanh Doan'],
    ],
  },
  {
    slug: 'ode-to-the-city',
    category: 'fashion-costume',
    title: 'ode to the city',
    subtitle: 'streetwear project - 2025',
    year: '2025',
    cover: odePortfolio[0],
    gallery: odePortfolio,
    photoshoot: odePhotoshoot,
    videoTitle: 'short film',
    filmUrl: 'https://youtu.be/LF3Y9lXnubM?si=619JAJko72gO8fbe',
    filmThumbnail: odePortfolio[0],
    description:
      'Formed through unique and diverse historical interchanges, Hanoi cultural landscape is trademarked by the parallel dynamic of East & West - past & future. Through the language of streetwear, Ode to the City celebrates the beauty of Hanoi as the fruitful and inimitable cradle of young artists on the raise, fusing local music memories, 70s punk fashion and meticulous traditional Hmong textiles.',
    credits: [
      ['creative director, fashion designer', 'Nora Wilde'],
      ['instructors', 'Lisa Shawgi, Tu Dang'],
      ['animation', 'Nora Wilde, from photos taken by Vu Viet Manh'],
      ['starring', 'Nam Thien'],
      ['photographer', 'Vu Viet Manh'],
      ['venue, lighting & props', 'Doan Hoai Nam & HUB Venue'],
      ['editor & vfx', 'Vu Ngoc'],
      ['sound designer', 'Katherine Vu'],
      ['graphic designer', 'Cao Sinh Tu'],
      ['m.u.a', 'Hiep Ciao'],
      ['support', 'Alice To, Laine'],
    ],
  },
  {
    slug: 'nothing-gold-can-stay-poster',
    category: 'visual-art',
    title: 'giữa mùa nước phơi trăng',
    subtitle: 'film poster illustration - 2026',
    year: '2026',
    cover: '/assets/real/img-6961.png',
    gallery: ['/assets/real/img-6961.png', '/assets/real/img-6962.png', '/assets/real/2.png'],
    description:
      'Giữa mùa nước phơi trăng (Nothing Gold Can Stay) is a drama short film by director Phương Bùi, made as part of her Film Directing BA. The illustration responds to the film’s memory, doubling and return through poster composition.',
    credits: [['illustration', 'Nora Wilde']],
  },
  {
    slug: 'ball-point-pen-series',
    category: 'visual-art',
    title: 'ball-point pen series',
    subtitle: 'pen on paper drawings - 2021-2023',
    year: '2021-2023',
    cover: ballPointGallery[0],
    gallery: ballPointGallery,
    imageInfo: ballPointInfo,
    description:
      'A collection of drawings using ball-point pen made during the on-and-off lockdown periods of my high school days.',
    credits: [['drawing', 'Nora Wilde']],
  },
  {
    slug: 'colored-series',
    category: 'visual-art',
    title: 'colored series',
    subtitle: 'colored paintings - 2021-2023',
    year: '2021-2024',
    cover: coloredGallery[0],
    gallery: coloredGallery,
    imageInfo: coloredInfo,
    description:
      'A collection of acrylic and watercolor paintings made during the on-and-off lockdown periods of my high school days.',
    credits: [['painting', 'Nora Wilde']],
  },
  {
    slug: 'hmong-project',
    category: 'research',
    title: 'hmong project',
    subtitle: 'material research - 2024',
    year: '2024',
    cover: '/assets/real/png-drive.png',
    gallery: ['/assets/real/png-drive.png', '/assets/real/creative-future-24.png', '/assets/real/creative-future-25.png'],
    description:
      'Research notes on craft, textile memory and the distance between preservation, authorship and contemporary fashion practice.',
    credits: [['research', 'Nora Wilde']],
  },
  {
    slug: 'of-us-and-arts',
    category: 'writing',
    title: 'of us and arts',
    subtitle: 'writing & translation - 2024',
    year: '2024',
    cover: '/assets/real/creative-future-27.png',
    gallery: ['/assets/real/creative-future-27.png', '/assets/real/2.png'],
    description:
      'Short texts and translations about artists, publics and the emotional labor of looking carefully.',
    credits: [['writing', 'Nora Wilde']],
  },
  {
    slug: 'bags',
    category: 'props-accessories',
    title: 'bags',
    subtitle: 'accessories study',
    year: '2024',
    cover: '/assets/real/nora-term-4640.png',
    gallery: ['/assets/real/nora-term-4640.png', '/assets/real/nora-term-4652.png'],
    description:
      'Small carrying structures where utility, prop language and soft sculpture meet.',
    credits: [['design', 'Nora Wilde']],
  },
  {
    slug: 'photo-notes',
    category: 'photography',
    title: 'photo notes',
    subtitle: 'photography archive',
    year: '2024',
    cover: '/assets/real/nora-term-4695.png',
    gallery: ['/assets/real/nora-term-4695.png', '/assets/real/nora-term-4703.png', '/assets/real/nora-term-4717.png'],
    description:
      'A compact archive of tests, references and quiet moments collected around studio and street life.',
    credits: [['photography', 'Nora Wilde']],
  },
  {
    slug: 'creative-direction-tests',
    category: 'creative-direction',
    title: 'image direction tests',
    subtitle: 'art direction sketches',
    year: '2025',
    cover: '/assets/real/nora-term-4721.png',
    gallery: ['/assets/real/nora-term-4721.png', '/assets/real/nora-term-4728.png', '/assets/real/nora-term-4935.png'],
    description:
      'Mood, casting, movement and composition tests for interdisciplinary shoots and stage-led image worlds.',
    credits: [['creative direction', 'Nora Wilde']],
  },
];

export const featuredPrints = [
  {
    id: 'denim-patch',
    title: 'fashion & costume',
    categorySlug: 'fashion-costume',
    image: '/assets/real/home/fashion-costume.png',
    x: 78,
    y: 72,
    rotate: 0,
    width: 330,
    z: 2,
  },
  {
    id: 'creative-direction',
    title: 'creative/art direction',
    categorySlug: 'creative-direction',
    image: '/assets/real/home/creative-direction.png',
    x: 44,
    y: 246,
    rotate: 0,
    width: 318,
    z: 5,
  },
  {
    id: 'artist-statement',
    title: 'artist statement',
    image: '/assets/real/home/artist-statement.png',
    x: -10,
    y: 430,
    rotate: 0,
    width: 250,
    z: 3,
  },
  {
    id: 'research',
    title: 'research',
    categorySlug: 'research',
    image: '/assets/real/home/research.png',
    x: 170,
    y: 388,
    rotate: 0,
    width: 268,
    z: 4,
  },
  {
    id: 'about',
    title: 'about',
    route: { name: 'about' },
    image: '/assets/real/home/about.png',
    x: 308,
    y: 88,
    rotate: 0,
    width: 302,
    z: 12,
  },
  {
    id: 'visual-art',
    title: 'visual art',
    categorySlug: 'visual-art',
    image: '/assets/real/home/visual-art.png',
    x: 514,
    y: 238,
    rotate: 0,
    width: 302,
    z: 9,
  },
  {
    id: 'contact',
    title: 'contact',
    route: { name: 'contact' },
    image: '/assets/real/home/contact.png',
    x: 622,
    y: 362,
    rotate: 0,
    width: 176,
    z: 8,
  },
  {
    id: 'writing',
    title: 'writing',
    categorySlug: 'writing',
    image: '/assets/real/of-us-and-arts.png',
    x: 430,
    y: 384,
    rotate: 0,
    width: 395,
    z: 6,
    hidden: true,
  },
  {
    id: 'photo',
    title: 'photography',
    categorySlug: 'photography',
    image: '/assets/real/img-6962.png',
    x: 612,
    y: 172,
    rotate: 0,
    width: 248,
    z: 7,
    hidden: true,
  },
];
